services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      RUBYOPT: -W:deprecated
      DB_HOST: db
    ports:
      - "3333:3000"
    volumes:
      - .:/rails
    tty: true
    stdin_open: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
