ARG RUBY_VERSION=3.3.6
FROM docker.io/library/ruby:$RUBY_VERSION-slim-bookworm AS base

ENV APP_ROOT="/rails"
ENV BUNDLE_PATH="/usr/local/bundle"
RUN mkdir -p ${APP_ROOT}
WORKDIR ${APP_ROOT}

RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y curl default-mysql-client libjemalloc2 libvips \
 && rm -rf /var/lib/apt/lists /var/cache/apt/archives

FROM base AS build

RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y build-essential \
    default-libmysqlclient-dev \
    git \
    pkg-config \
 && rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile Gemfile.lock ${APP_ROOT}/

RUN bundle install \
 && rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git

COPY . ${APP_ROOT}

FROM base

COPY --from=build ${BUNDLE_PATH} ${BUNDLE_PATH}
COPY --from=build ${APP_ROOT} ${APP_ROOT}

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

ENV BINDING="0.0.0.0"
EXPOSE 3000

CMD ["./bin/rails", "server"]
